// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqwdtbjecgpwbjpyvyrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxd2R0YmplY2dwd2JqcHl2eXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTYyNDgsImV4cCI6MjA2MDQ5MjI0OH0.UOl2fDrFJkRSBItmUixpWfWqzTEbaqyFt5qO8SF5Y78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);